### ISSUE TITLE
Error with Quickstart code

### ISSUE THREAD

**Issue by pguardiario** [llm-tools/embedJs#165]
### 🐛 Describe the bug

In Line 12:
ragApplication.addLoader({ urlOrContent: 'https://www.forbes.com/profile/elon-musk' })
it's causing this
Uncaught TypeError TypeError: loader.getUniqueId is not a function
    at _addLoader (c:\cygwin64\home\pguar\node\llm\node_modules\.pnpm\@llm-tools+embedjs@0.1.17_@langchain+core@0.3.17\node_modules\@llm-tools\embedjs\src\core\rag-application.js:140:33)
    at addLoader (c:\cygwin64\home\pguar\node\llm\node_modules\.pnpm\@llm-tools+embedjs@0.1.17_@langchain+core@0.3.17\node_modules\@llm-tools\embedjs\src\core\rag-application.js:127:21)
    at <anonymous> (c:\cygwin64\home\pguar\node\llm\test.mjs:12:16)
    at processTicksAndRejections (<node_internals>/internal/process/task_queues:95:5)

**Comment by adhityan** [comment]
Yes. The QuickStart is updated. And yes, the loaders need to be awaited. The quick start reflects this correctly now.
